export const AMPLIFY_AUTH_STEPS = {
  CONFIRM_SIGN_IN: "CONFIRM_SIGN_IN_WITH_NEW_PASSWORD_REQUIRED",
  CONFIRM_SIGN_UP: "CONFIRM_SIGN_UP",
  CONFIRM_ATTRIBUTE: "CONFIRM_ATTRIBUTE_WITH_CODE",
  DONE: "DONE",
  STATUS_CONFIRMED: "status is CONFIRMED",
};
